import './globals.css';
import { Inter } from 'next/font/google';
import type { ReactNode } from 'react';
import { SessionProvider } from '@/components/provider/sessionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Library',
	description: 'Generated by create next app',
};

type LayoutProps = {
	children: ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<SessionProvider>{children}</SessionProvider>
			</body>
		</html>
	);
}
