import type { ReactNode } from 'react';
import { ProtectedPage } from '@/components/protectedPage/protectedPage';

export const metadata = {
	title: 'Library',
	description: 'Generated by create next app',
};

type LayoutProps = {
	children: ReactNode;
};

const DashboardLayout = ({ children }: LayoutProps) => {
	return (
		<ProtectedPage>
			<main className="h-screen">{children}</main>
		</ProtectedPage>
	);
};

export default DashboardLayout;
