import type {ReactNode} from 'react';
import {ProtectedPage} from '@/components/protectedPage/protectedPage';
import {Header} from '@/components/header/header';
import {Footer} from '@/components/footer/footer';
import {Container} from "@/components/container/container";
import {NavLink} from "@/components/navLink/navLink";

export const metadata = {
    title: 'Library',
    description: 'Generated by create next app',
};

type LayoutProps = {
    children: ReactNode;
};

const navLinks: NavLink[] = [
    {href: '/your-profile', label: 'Your data'},
    {href: '/change-password', label: 'Change password'},
    {href: '/my-renatls', label: 'My rentals'},
    {href: '/my-reservations', label: 'My reservations'},
    {href: '/settings', label: 'Settings'},
    {href: '/logout', label: 'Logout'},
];

const DashboardLayout = ({children}: LayoutProps) => {
    return (
        <ProtectedPage>
            <Header/>
            <main className="min-h-screen"><Container>
                <div className='flex w-full flex-col md:flex-row'>
                    <section className='w-full md:w-1/4'>
                        <nav>
                            <ul>
                                {navLinks.map((link, i) => (
                                    <li>
                                        <NavLink key={i} label={link.label} href={link.href}/>
                                    </li>))}
                            </ul>
                        </nav>
                    </section>
                    <section className='w-full md:w-2/4 md:px-20'>
                        {children}
                    </section>
                </div>
            </Container></main>
            <Footer/>
        </ProtectedPage>
    );
};

export default DashboardLayout;
