import '../globals.css'
import { Inter } from 'next/font/google'
import clsx from 'clsx'
import type { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Library',
  description: 'Generated by create next app',
}

type LayoutProps = {
    children: ReactNode
}

const LoginLayout = ({
  children,
}: LayoutProps) => {
  return (
        <main className="h-screen">
        {children}
        </main>
  )
}

export default LoginLayout
