import type { ReactNode } from 'react';

export const metadata = {
	title: 'Library',
	description: 'Generated by create next app',
};

type LayoutProps = {
	children: ReactNode;
};

const LoginLayout = ({ children }: LayoutProps) => {
	return <main className="h-screen">{children}</main>;
};

export default LoginLayout;
